place report folder on temp

diff --git a/.github/workflows/scan-and-report.yml b/.github/workflows/scan-and-report.yml
--- a/.github/workflows/scan-and-report.yml
+++ b/.github/workflows/scan-and-report.yml
@@ -25,7 +25,7 @@ jobs:
               
             - name: Setup Report Repository and Get AGENT MD FILE
               run: |
-                git clone "https://x-access-token:$REPORT_REPO_TOKEN@github.com/willdo-naywin/VULN-REPORT.git" /report
+                git clone "https://x-access-token:$REPORT_REPO_TOKEN@github.com/willdo-naywin/VULN-REPORT.git" /tmp/report
 
             - name: Checkout target-repo main branch 
               uses: actions/checkout@v4
@@ -45,18 +45,18 @@ jobs:
               env: 
                 COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
               run: |
-                [ -f "/report/.github/agents/security-agent.md" ] || { echo "Error: security-agent.md not found"; exit 1; }
-                PROMPT="$(cat  /report/.github/agents/security-agent.md )"
+                [ -f "/tmp/report/.github/agents/security-agent.md" ] || { echo "Error: security-agent.md not found"; exit 1; }
+                PROMPT="$(cat  /tmp/report/.github/agents/security-agent.md )"
                 PROMPT+=$'\n\nContext:\n'
                 PROMPT+="- Repository: $CURRENT_REPO"
                 PROMPT+=$'\n\nTask:\n'
                 PROMPT+=$"\n- $CVEについて現レポジトリ全体にあるコードを確認し、脆弱性レポートを作成してください。"
-                PROMPT+=$'\n- 作成したレポートは　/report/vuln-reports/$DATE/$CURRENT_REPO/'$CVE'-脆弱性報告.md に保存してください。'
+                PROMPT+=$'\n- 作成したレポートは　/tmp/report/vuln-reports/$DATE/$CURRENT_REPO/'$CVE'-脆弱性報告.md に保存してください。'
                 copilot --prompt "$PROMPT" --allow-all-tools --allow-all-paths < /dev/null
 
             - name: Push to report-repo
               run: |
-                cd /report
+                cd /tmp/report
                 git config user.name "report-bot"
                 git config user.email "bot@example.com"                
                 git add .
